name: 'Create Pull Request Wrapper'
description: 'Wrapper for peter-evans/create-pull-request'
inputs:
  token:
    description: 'GitHub token'
    required: true
  branch:
    description: 'Branch name'
    required: true
  title:
    description: 'Pull request title'
    required: true
  body:
    description: 'Pull request body'
    required: false
  commit-message:
    description: 'Commit message'
    required: false
  base:
    description: 'Base branch'
    required: false
  delete-branch:
    description: 'Delete branch'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Create Pull Request'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.token }}
        branch: ${{ inputs.branch }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        commit-message: ${{ inputs.commit-message }}
        base: ${{ inputs.base }}
        delete-branch: ${{ inputs.delete-branch }}
