name: Build and Test
description: Build, Restore, and Test
inputs:
  gh-packages-token:
    description: Github packages token
    required: true
  solution-file:
    description: The solution file name with relative path
    required: true
  dotnet-version:
    description: The version of .NET for Setup task
    default: 6.0.*
    required: false
runs:
  using: composite
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        include-prerelease: true
        
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
  
    - name: Restore
      working-directory: ./src
      shell: bash
      run: >-
        dotnet nuget add source --username USERNAME --password ${{ inputs.gh-packages-token }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/tesourohq/index.json
        && dotnet restore ${{ inputs.solution-file }}

    - name: Build
      working-directory: ./src
      shell: bash
      run: dotnet build --no-restore -c Release ${{ inputs.solution-file }}

    - name: Test
      working-directory: ./src
      shell: bash
      run: dotnet test --no-build -c Release -l 'trx;LogFileName=${{ runner.temp }}/results.trx' ${{ inputs.solution-file }} --collect:"XPlat Code Coverage" --results-directory ${{ runner.temp }}

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: ${{ runner.temp }}/results.trx
        reporter: dotnet-trx
        
    - name: Copy Coverage To Predictable Location
      shell: bash
      run: cp --backup=t ${{ runner.temp }}/*/coverage.cobertura.xml ${{ runner.temp }}
      
    - name: List temp location
      shell: bash
      run: ls ${{ runner.temp }}
      
    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ runner.temp }}/coverage.cobertura.xml~1~,${{ runner.temp }}/coverage.cobertura.xml
        badge: true
        format: 'markdown'
        output: 'both'
        thresholds: '30 75'
        fail_below_min: true
