name: Build docker images
description: Build docker images
inputs:
  sem-ver:
    description: Version of the package
    required: true
  gh-packages-token:
    description: Github packages token
    required: true
runs:
  using: composite
  steps:
    - name: Authorize with GCloud
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: access_token
        workload_identity_provider: projects/274784588410/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc-provider
        service_account: spinnaker-gcr-account@tesouro-cloud.iam.gserviceaccount.com
    
    - name: Set up GCloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
    
    - name: Configure GCloud for Docker
      shell: bash
      run: gcloud auth configure-docker -q
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Docker Meta
      id: docker_meta_pr
      env:
        GCR_REGISTRY: gcr.io/tesouro-cloud
        CONTAINER_NAME: "tesouro-service-card-processing${{ github.event_name == 'pull_request' && '-ci' || '' }}"
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.GCR_REGISTRY }}/${{ env.CONTAINER_NAME }}
        tags: |
          ${{ inputs.sem-ver }}
    
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Tesouro.Payments.Service.CardProcessing/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.docker_meta_pr.outputs.tags }}
        build-args: "GH_PACKAGES_TOKEN=${{ inputs.gh-packages-token }}"
