name: Create Release
description: Create Release
inputs:
  sem-ver:
    description: Version of the package
    required: true
  github-token:
    description: Github token
    required: true
runs:
  using: composite
  steps:
    - name: Create Release
      id: create_release
      if: github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      with:
        tag_name: ${{ inputs.sem-ver }}
        draft: false
