name: 'GitHub App Token Wrapper'
description: 'Wrapper for tibdex/github-app-token'
inputs:
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'Private key'
    required: true
runs:
  using: 'composite'
  outputs:
    token: ${{ steps.generate_token.outputs.token }}
  steps:
    - name: 'GitHub App Token'
      id: generate_token
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}
