name: 'GitHub App Token Wrapper'
description: 'Wrapper for tibdex/github-app-token'
inputs:
  app_id:
    description: 'GitHub App ID'
    required: true
  private_key:
    description: 'Private key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'GitHub App Token'
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ inputs.app_id }}
        private_key: ${{ inputs.private_key }}
