name: 'Install AWS CLI Wrapper'
description: 'Wrapper for unfor19/install-aws-cli-action'
runs:
  using: 'composite'
  steps:
    - name: 'Install AWS CLI'
      uses: unfor19/install-aws-cli-action@v1