name: Get Version
description: Determine Version
outputs:
  SemVer:
    description: Semantic Version
    value: ${{ steps.gitversion.outputs.SemVer }}
  legacySemVerPadded:
    description: Semantic Version Padded
    value: ${{ steps.gitversion.outputs.legacySemVerPadded }}
  nuGetVersionV2:
    description: Nuget Version
    value: ${{ steps.gitversion.outputs.nuGetVersionV2 }}
runs:
  using: composite
  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: "5.7.0"

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
