name: 'Amazon ECR Login Wrapper'
description: 'Wrapper for aws-actions/amazon-ecr-login'
outputs:
  registry:
    description: 'ECR registry URL'
    value: ${{ steps.ecr-login.outputs.registry }}
runs:
  using: 'composite'
  steps:
    - name: 'Amazon ECR Login'
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2

    - name: Debug Registry Output
      shell: bash
      run: | 
        echo "Registry URL in action: ${{ steps.ecr-login.outputs.registry }}"
           
