name: Cosmo GraphQL Check
description: Check and Publish Graphql Schema for breaking changes and visibility
inputs:
  cosmo_api_key:
    description: Cosmo API Key
    required: true
  cosmo_api_url:
    description: Cosmo API Url
    required: true
  cosmo_cdn_url:
    description: Cosmo CDN Url
    required: true
  cosmo_web_url:
    description: Cosmo Web Url
    required: true
  subgraph_name:
    description: Subgraph Name
    required: true
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"

    - name: Install Cosmo CLI
      shell: bash
      run: |
        npm install -g wgc@latest

    - uses: actions/download-artifact@v4
      with:
        name: ${{inputs.subgraph_name}}-subgraph.graphql

    - name: Run subgraph check staging
      shell: bash
      if: always()
      run: |
        echo '---' >> $GITHUB_STEP_SUMMARY
        echo '### **Subgraph check against staging composition!** 🚀' >> $GITHUB_STEP_SUMMARY
        echo '---' >> $GITHUB_STEP_SUMMARY
        wgc subgraph check ${{inputs.subgraph_name}} --namespace staging --schema ${{inputs.subgraph_name}}-subgraph.graphql &> ${{github.workspace}}/staging-composition.logs
        cat ${{github.workspace}}/staging-composition.logs
        cat ${{github.workspace}}/staging-composition.logs >> $GITHUB_STEP_SUMMARY
      env:
        COSMO_API_KEY: ${{ inputs.cosmo_api_key }}
        COSMO_API_URL: ${{ inputs.cosmo_api_url }}
        COSMO_CDN_URL: ${{ inputs.cosmo_cdn_url }}
        COSMO_WEB_URL: ${{ inputs.cosmo_web_url }}

    - name: Run subgraph check production
      shell: bash
      if: always()
      run: |
        echo '---' >> $GITHUB_STEP_SUMMARY
        echo '### **Subgraph check against production composition!** 🚀' >> $GITHUB_STEP_SUMMARY
        echo '---' >> $GITHUB_STEP_SUMMARY
        wgc subgraph check ${{inputs.subgraph_name}} --namespace production --schema ${{inputs.subgraph_name}}-subgraph.graphql &> ${{github.workspace}}/production-composition.logs
        cat ${{github.workspace}}/production-composition.logs
        cat ${{github.workspace}}/production-composition.logs >> $GITHUB_STEP_SUMMARY
      env:
        COSMO_API_KEY: ${{ inputs.cosmo_api_key }}
        COSMO_API_URL: ${{ inputs.cosmo_api_url }}
        COSMO_CDN_URL: ${{ inputs.cosmo_cdn_url }}
        COSMO_WEB_URL: ${{ inputs.cosmo_web_url }}

    - name: Exit override by label
      shell: bash
      if: always() && contains(github.event.pull_request.labels.*.name, 'expected-breaking-federation-validation') || github.event.pull_request.labels.*.name, 'expected-breaking-graphql-validation') || github.event_name == 'merge_group' }}
      run: |
        exit 0