name: Slack Notify
description: Send notifications to Slack on actions failure.
inputs:
  slack_webhook_url:
    description: Slack webhook url.
    required: true
runs:
  using: composite
  steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }} # required
      if: failure() || cancelled() # Pick up events only on failure or cancellation.