name: Slack Notify
description: Send notifications to Slack on actions failure.
inputs:
  slack-webhook-url:
    description: Slack webhook url.
    required: true
runs:
  using: composite
  steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: 'failure'
        username: 'GHA-Slack-Notifybot'
        icon_emoji: ':ahhhhhhhhh:'
        fields: repo,message,commit,author,action,eventName,ref,workflow,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }} # required