name: Validate GraqhQL
description: Validate Graphql Schema for breaking changes and visibility
inputs:
  path-to-graphql-schema:
    description: Path to graphql schema.
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: kamilkisiela/graphql-inspector@91cefc9d934ccac1b4be9f26f44b6f533c300247
      with:
        name: Inspect and Validate GraphQL
        schema: "main:${{inputs.path-to-graphql-schema}}"