name: 'Upload Artifact Wrapper'
description: 'Wrapper for actions/upload-artifact@v4'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Path to upload'
    required: true
runs:
  using: 'composite'
  steps:
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}