name: 'Upload Artifact Wrapper'
description: 'Wrapper for actions/upload-artifact'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Path to upload'
    required: true
  if-no-files-found:
    description: 'What to do if no files are found'
    required: false
    default: 'warn'
runs:
  using: 'composite'
  steps:
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        if-no-files-found: ${{ inputs.if-no-files-found }}