name: Armory Deploy
description: Deploy using Armory CDaaS
inputs:
  armory-client-id:
    description: Client ID, configured in the Armory account being used.
    required: true
  armory-client-secret:
    description: Client Secret, corresponding to the Client ID.
    required: true
  armory-yaml-path:
    description: Path to the armory-deployment.yaml file.
    required: true
  prod-kustomize-path:
    description: Path from the project root to the production kustomize overlay.
    required: true
  stage-kustomize-path:
    description: (Optional) Path from the project root to the stage kustomize overlay.
    required: false
  major-minor-patch:
    description: SemVer, with nothing other than 'major.minor.patch'.
    required: true
  image-tag:
    description: Tag of the image that should be used in the deployment manifest.
    required: true
runs:
  using: composite
  steps:
    - name: Setup Kustomize
      shell: bash
      working-directory: deployment/kustomize/base
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - name: Update Version Label
      shell: bash
      working-directory: deployment/kustomize/base
      run: kustomize edit set label version:${{ inputs.major-minor-patch }} && kustomize edit set image gcr.io/tesouro-cloud/tesouro-service-reporting:${{ inputs.image-tag }}

    - name: Bake Stage Manifests
      if: inputs.stage-kustomize-path != '' # Only run if the path is provided, otherwise assume no stage environment is being used.
      shell: bash
      run: kustomize build ${{ inputs.stage-kustomize-path }} -o stage-manifests.yaml  # As with prod below, this requires the armory-deployment.yaml to look in the project root for the manifest, at this name.

    - name: Bake Prod Manifests
      shell: bash
      run: kustomize build ${{ inputs.prod-kustomize-path }} -o prod-manifests.yaml

      # https://docs.armory.io/cd-as-a-service/setup/gh-action/
    - name: Deploy
      id: armory-deploy
      uses: armory/cli-deploy-action@v1.0.0
      with:
        clientId: ${{ inputs.armory-client-id }}
        clientSecret: ${{ inputs.armory-client-secret }}
        path-to-file: ${{ inputs.armory-yaml-path }}
      env:
        URL: ${{ steps.armory-deploy.outputs.deployment-link }}
    - name: Update Summary with Deployment link
      shell: bash
      run: "echo :rocket: Deployment URL: $URL >> $GITHUB_STEP_SUMMARY"
