name: Armory Deploy
description: Deploy using Armory CDaaS
inputs:
  armory-client-id:
    description: Client ID, configured in the Armory account being used.
    required: true
  armory-client-secret:
    description: Client Secret, corresponding to the Client ID.
    required: true
  armory-yaml-path:
    description: Path to the armory-deployment.yaml file.
    required: true
  stage-kustomize-path:
    description: Path from the project root to the stage kustomize overlay.
    required: true
  stage-kustomize-output-path:
    description: Path to the baked stage manifest yaml file
    required: false
    default: stage-manifests.yaml
  prod-kustomize-path:
    description: Path from the project root to the production kustomize overlay.
    required: true
  prod-kustomize-output-path:
    description: Path to the baked prod manifest yaml file
    required: false
    default: prod-manifests.yaml
  working-directory:
    description: Working directory for the kustomize edit steps
    required: false
    default: deployment/kustomize/base
runs:
  using: composite
  steps:
    - name: Setup Kustomize
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash

    - name: Bake Stage Manifests
      shell: bash
      run: kustomize build ${{ inputs.stage-kustomize-path }} -o ${{ inputs.stage-kustomize-output-path }}

    - name: Bake Prod Manifests
      shell: bash
      run: kustomize build ${{ inputs.prod-kustomize-path }} -o ${{ inputs.prod-kustomize-output-path }}

      # https://docs.armory.io/cd-as-a-service/setup/gh-action/
    - name: Deploy
      id: armory-deploy
      uses: armory/cli-deploy-action@main
      with:
        clientId: ${{ inputs.armory-client-id }}
        clientSecret: ${{ inputs.armory-client-secret }}
        path-to-file: ${{ inputs.armory-yaml-path }}
        waitForDeployment: true
