name: Branch Locking
description: Lock or unlock repo branches
inputs:
  app-id:
    description: Github APP ID with permissions for branch protections control.
    required: true
  app-pem:
    description: Github APP PEM with permissions for branch protections control.
    required: true
  branch-name:
    description: Branch name.
    required: true
  lock-state:
    description: Desired branch lock state. Defaults to unlocked. Pass string of true or false.
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Generate a token
      id: generate_token
      if: github.ref == 'refs/heads/main'
      uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-pem }}

    - name: Set the branch lock
      env:
        token: ${{ steps.generate_token.outputs.token }}
        repo: ${{ github.repository }}
        branch: ${{ inputs.branch-name }}
        state: ${{ inputs.lock-state }}
      shell: bash
      if: github.ref == 'refs/heads/main'
      run: |
        curl -s -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: token $token" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$repo/branches/$branch/protection \
        -d "$(curl -s -L \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${token}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/$repo/branches/$branch/protection \
        | jq --argjson lock_state $state '.lock_branch.enabled = $lock_state' \
        | jq 'del(.url, .required_signatures.url, .enforce_admins.url, .required_pull_request_reviews.url, .required_status_checks.url, .required_status_checks.contexts_url, .required_status_checks.checks)' \
        | jq '. += { "restrictions": null }' \
        | jq -r '.enforce_admins.enabled as $ea | .enforce_admins = $ea | .lock_branch.enabled as $lb | .lock_branch = $lb | .allow_fork_syncing.enabled as $afs | .allow_fork_syncing = $afs | .allow_force_pushes.enabled as $afp | .allow_force_pushes = $afp | .require_linear_history.enabled as $rlh | .require_linear_history = $rlh | .allow_deletions.enabled as $ad | .allow_deletions = $ad | .required_signatures.enabled as $rs | .required_signatures = $rs | .required_linear_history.enabled as $rlh | .required_linear_history = $rlh | .required_conversation_resolution.enabled as $rcr | .required_conversation_resolution = $rcr | .block_creations.enabled as $bc | .block_creations = $bc')"
