name: 'Checkout Wrapper'
description: 'Wrapper for actions/checkout@v4'
inputs:
  repository:
    description: 'Repository'
    required: false
  ref:
    description: 'Ref'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}