name: 'Checkout Wrapper'
description: 'Wrapper for actions/checkout@v4'
inputs:
  fetch-depth:
    description: 'How many commits to fetch'
    required: false
runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}