name: 'Checkout Wrapper'
description: 'Wrapper for actions/checkout'
inputs:
  clean:
    description: 'Whether to execute `git clean -ffdx && git reset --hard HEAD` before fetching'
    default: true
  fetch-depth:
    description: 'How many commits to fetch'
    required: false
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is configured
      with the local git config, which enables your scripts to run authenticated git
      commands. The post-job step removes the PAT.
      
      
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
      
      
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v4
      with:
        clean: ${{ inputs.clean }}
        fetch-depth: ${{ inputs.fetch-depth }}
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}