name: ArgoCD Deploy
description: Deploy using ArgoCD
inputs:
  argocd-application-name:
    description: ArgoCD application name, must match the application manifest.
    required: true
  argocd-apikey:
    description: ArgoCD service account api-key.
    required: true
  argocd-host:
    description: ArgoCD host.
    required: true
  github-token:
    description: CI github token.
    required: true
  ci-username:
    description: CI github username.
    required: true
  ci-email:
    description: CI github email.
    required: true
  semver:
    description: Semantic Version.
    required: true
  image-name:
    description: Tagged image name to be deployed.
    required: true
  path-to-version-patch:
    description: Path to kubernetes kustomize base deployment yaml.
    required: false
    default: ''
  path-to-overlays:
    description: Path to kubernetes kustomize overlays.
    required: true
  path-to-db-base:
    description: Path from the project root to the database migration kustomize base.
    required: false
    default: ''
  path-to-db-overlays:
    description: Path from the project root to the database migration kustomize overlays.
    required: false
    default: ''
  service-name:
    description: Path from the project root to the database migration kustomize overlays.
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: CheckoutRepo
      uses: actions/checkout@v3
      with:
        token: ${{ inputs.github-token }}
        fetch-depth: 0

    - name: Set short sha
      shell: bash
      id: shortsha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # Commit and push.
    - name: Apply semver-sha to version
      shell: bash
      # Only run on main branch push (e.g. pull request merge).
      if: github.ref == 'refs/heads/main'
      run: |
        git config --global user.name "${{ inputs.ci-username }}"
        git config --global user.email "${{ inputs.ci-email }}"
        git checkout release
        git merge -Xtheirs --no-commit main

    - name: Version microservice
      shell: bash
      if: github.ref == 'refs/heads/main' && inputs.path-to-version-patch != ''
      run: |
        yq -i '.spec.template.metadata.labels.version = "${{ inputs.semver }}.${{ github.run_attempt }}-${{ github.sha }}"' ${{ inputs.path-to-version-patch }}
        yq -i '.spec.template.spec.containers[0].image = "${{ inputs.image-name }}"' ${{ inputs.path-to-version-patch }}
    
    - name: Version db job name
      shell: bash
      if: github.ref == 'refs/heads/main' && inputs.path-to-db-overlays != '' && inputs.path-to-db-base != '' && inputs.service-name != ''
      run: |
        yq -i '.metadata.name = "${{ inputs.service-name }}-database-job-${{ steps.shortsha.outputs.sha_short }}-${{github.run_attempt}}"' ${{ inputs.path-to-db-base }}job.yaml
        for dir in ${{ inputs.path-to-db-overlays }}*/; do yq -i '.metadata.name = "${{ inputs.service-name }}-database-job-${{ steps.shortsha.outputs.sha_short }}-${{github.run_attempt}}"' "$dir""/job.yaml"; done

    - name: Version overlays
      shell: bash
      if: github.ref == 'refs/heads/main' && inputs.path-to-overlays != ''
      run: |
        for dir in ${{ inputs.path-to-overlays }}*/; do yq e '.labels.[0].pairs.semver = "${{ inputs.semver }}"' -i "$dir""kustomization.yaml"; yq e '.labels.[0].pairs."app.kubernetes.io/version" = "${{ inputs.semver }}"' -i "$dir""kustomization.yaml"; done

    - name: Commit and push
      shell: bash
      # Only run on main branch push (e.g. pull request merge).
      if: github.ref == 'refs/heads/main'
      run: |
        git commit -a -m "Version ${{ inputs.semver }}.${{ github.run_attempt }}-${{ github.sha }}"
        git push

    - name: Deploy
      if: github.ref == 'refs/heads/main' # Only on main.
      id: argocd-deploy
      shell: bash
      run: |
        curl -s -X POST "${{ inputs.argocd-host }}/api/v1/applications/${{ inputs.argocd-application-name }}/sync" -H "Authorization: Bearer ${{ inputs.argocd-apikey }}" | jq