name: Notify Spinnaker
description: Notify Spinnaker
inputs:
  sem-ver:
    description: Version of the package
    required: true
  spinnaker-webhook-url:
    description: The Spinnaker webhook URL
    required: true
  github-repo:
    description: The GitHub repo URL
    required: true
  image-name:
    description: Name of the image in the container repository
    required: true
runs:
  using: composite
  steps:
    - name: Notify Spinnaker
      id: notify_spinnaker
      if: github.ref == 'refs/heads/main'
      uses: fjogeleit/http-request-action@v1
      with:
        url: '${{ inputs.spinnaker-webhook-url }}'
        method: 'POST'
        data:  |
          {
            "artifacts": [
              {
                  "customKind": false,
                  "reference": "${{ intpus.github-repo }}",
                  "artifactAccount": "ci-tesouro",
                  "type": "git/repo",
                  "version": "${{ github.GITHUB_REF }}"
              },
              {
                  "customKind": false,
                  "reference": "gcr.io/tesouro-cloud/${{ inputs.image-name }}:${{ inputs.sem-ver }}",
                  "name": "gcr.io/tesouro-cloud/${{ inputs.image-name }}",
                  "artifactAccount": "docker-registry",
                  "type": "docker/image",
                  "version": "${{ inputs.sem-ver }}"
              }
            ]
          }
  
    - name: Show Response
      shell: bash
      run: echo ${{ steps.notify_spinnaker.outputs.response }}
